version: '3.8'

services:
  app:
    container_name: fastapi-sinai
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - postgresql_default
    command: /bin/bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

networks:
  postgresql_default:
    external: true
    name: postgresql_default
  